
name: Build and Deploy GhPages docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.0

      - name: Build
        run: sbt readme/run

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: readme/target/scalatex
